### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by xiongtongzi** [cornerstonejs/codecs#33]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/19956089/233012270-3888d4a3-438a-4167-b239-9cc1e4512327.png">
I have installed version 0.1.9 of @cornerstonejs/dicom-codec in my project. After the installation, errors were reported indicating that corresponding files could not be found at:

@cornerstonejs/codec-charls/wasmjs in ./node_modules/@cornerstonejs/dicom-codec/src/codecs/jpegls.js
@cornerstonejs/codec-libjpeg-turbo-8bit/wasmjs in ./node_modules/@cornerstonejs/dicom-codec/src/codecs/libjpegTurbo8bit.js
@cornerstonejs/codec-openjpeg/wasmjs in ./node_modules/@cornerstonejs/dicom-codec/src/codecs/jpeg2000.js

I suspect that the package versions on which your npm package depends may not correspond correctly.

**Comment by wayfarer3130** [comment]
I believe that issue was transient and resolved in 0.1.10

**Comment by wayfarer3130** [comment]
As noted, I believe this is resolved in later version - there was a known issue there.
