### ISSUE TITLE
Add dispatch logic

### ISSUE THREAD

**Issue by chafey** [cornerstonejs/codecs#36]
A very common use case is to decompress a given image frame given the compressed bitstream and the transfer syntax.  These could be obtained in a variety of ways such as by parsing the DICOM P10 file (e.g. with dicomParser), via DICOMweb, etc.  Currently this dispatch logic is in cornerstoneWADOImageLoader making it difficult to use independently of cornerstone.  Ideally that dispatch logic would be added to this library so it could be more easily reused.  The logic is here:

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/shared/decodeImageFrame.js

**Comment by chafey** [comment]
@wayfarer3130 @sedghi can you add your thoughts on this?  I am happy to do the work

**Comment by sedghi** [comment]
Maybe this would be helpful https://github.com/cornerstonejs/codecs/tree/main/packages/dicom-codec

**Comment by chafey** [comment]
Learned this is already implemented, closing !
