### ISSUE TITLE
jpegLosslessCodec decode error

### ISSUE THREAD

**Issue by devkumarsingh-qure** [cornerstonejs/codecs#48]
![Screenshot 2024-10-03 at 5 53 33 PM](https://github.com/user-attachments/assets/5007599d-cbb2-444b-9619-73274ca10259)

I am trying to use https://github.com/RadicalImaging/Static-DICOMWeb for hosting a dicomwebserver and decoding/encoding.

For dicoms with transfer syntax "1.2.840.10008.1.2.4.70" which use "jpeg-lossless-decoder-js" codec, I am facing the above error.

![Screenshot 2024-10-03 at 6 06 48 PM](https://github.com/user-attachments/assets/ec645702-1693-437b-a81d-baaeab6600b2)

codec: codecModule["lossless"] is undefined.

**Comment by sedghi** [comment]
Can you check the latest OHIF viewer, which now includes Cornerstone 3D 2.0?

Here are the migration guides:

Try OHIF locally: [https://viewer-dev.ohif.org/localbasic](https://viewer-dev.ohif.org/localbasic)<br>Try Cornerstone3D 2.0 locally: [https://www.cornerstonejs.org/live-examples/local.html](https://www.cornerstonejs.org/live-examples/local.html)

[https://docs.ohif.org/migration-guide/3p8-to-3p9/](https://docs.ohif.org/migration-guide/3p8-to-3p9/)
